name: Renovate

on:
  schedule:
    - cron: "0 3 * * *" # Run daily at 3:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Renovate
        uses: renovatebot/github-action@v38.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}